### PR TITLE
Property tree

### PR DESCRIPTION
**Pull request by imane-aanna**

### CODE REVIEW

**Comment by pradal** [comment]
@imane-aanna : Can I closed this PR?

**Comment by imane-aanna** [comment]
@pradal  : I thought this would be the branch I will work on through the whole process of creating the Properting Tree class (Attributes + Methods).

**Comment by pradal** [comment]
OK.
Let's do this way.

**Comment by imane-aanna** [comment]
@pradal : I have added all the functions starting from : https://github.com/pradal/mtg/blob/master/src/mtg/tree.py#L698 (except graph_properties because I didn't understand what it did).
I also have a question for the function AddVertexProperty(). You will find it here : https://github.com/openalea-incubator/csMTG/pull/24/commits/7ad01fe2a2677a3144c57a0bb6f882a1a7b8c07f

Could you please review all the changes I made and make sure that the functions are indeed returning what they are meant to ?

Thank you.

**Comment by pradal** [comment]
@imane-aanna : Some functions are defined for compatibility with the graph API.
We may discuss on the meaning of each function.

**Comment by imane-aanna** [comment]
@pradal : I have already coded all the other functions, based on the comments and what I understood.

**Comment by pradal** [comment]
@imane-aanna : good work. Congrats.

**Pull request merged**
